---
title: "best1634"
author: "GG"
date: "2/27/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
library(janitor)
library(dbplyr)
```
```{r}
final_best <- read_csv("~/github/BEST_data/data/fish_tidy_best.csv")
head(final_best)
final_best[ final_best == 0] <-NA
```

Contrtibute of each trophic guild to biomass at each site
```{r}
ggplot(data = final_best, aes(x = site, y=biomass, fill = trophic_guild)) + geom_bar(stat = "summary", fun.y = "mean", position = "fill") + scale_fill_brewer(palette = "Dark2") + scale_y_continuous(name = "Percent Biomass", labels=c("0", "25", "50", "75", "100")) + theme_bw() + labs(x="")
```

```{r}
ggplot(data = final_best, aes(x = survey, y=biomass, fill = trophic_guild)) + geom_bar(stat = "summary", fun.y = "mean", position = "fill") + scale_fill_brewer(palette = "Dark2") + scale_x_discrete(name = "Survey Number", limits=c("1", "2", "3", "4", "5", "6")) + scale_y_continuous(name = "Percent Biomass", labels=c("0", "25", "50", "75", "100")) + theme_bw() + labs(x="")
```

```{r}
ggplot(data = final_best, aes(x = survey, y=biomass, fill = trophic_guild)) + geom_bar(stat = "summary", fun.y = "mean", position = "stack") + scale_fill_brewer(palette = "Dark2") + scale_x_discrete(name = "Survey Number", limits=c("1", "2", "3", "4", "5", "6")) + theme_bw() + labs(y="Mean Biomass(g)")

```


Mean biomass of each trophic group per survey per site
```{r}
ggplot(data = final_best, aes(x = survey, y=biomass, fill = trophic_guild)) + geom_bar(stat = "summary", fun.y = "mean", position = "fill") + scale_fill_brewer(palette = "Dark2") + facet_grid(site~., scales = "free") + scale_x_discrete(name = "Survey Number", limits=c("1", "2", "3", "4", "5", "6")) + scale_y_continuous(name = "Percent Biomass", labels=c("0", "25", "50", "75", "100"))+ theme_bw()
```


```{r}
anovatg <- aov(sqrt(biomass) ~ as.character(trophic_guild) * site * as.character(survey), data = final_best)
summary.aov(anovatg)
TukeyHSD(anovatg)
```
```{r}
plankto_bio <- subset(final_best, trophic_guild=="planktivore")
anovatgpbio <- aov(sqrt(biomass) ~ site + as.character(survey), data = plankto_bio)
summary.aov(anovatgpbio)
TukeyHSD(anovatgpbio)
```
```{r}
carno_bio <- subset(final_best, trophic_guild=="macro_carnivore")
anovatgcbio <- aov(sqrt(biomass) ~ site + as.character(survey), data = carno_bio)
summary.aov(anovatgcbio)
TukeyHSD(anovatgcbio)
```

```{r}
inverto_bio <- subset(final_best, trophic_guild=="invertivore")
anovatgibio <- aov(sqrt(biomass) ~ site + as.character(survey), data = inverto_bio)
summary.aov(anovatgibio)
TukeyHSD(anovatgibio)
```

```{r}
herbi_bio <- subset(final_best, trophic_guild=="herbivore")
anovatghbio <- aov(sqrt(biomass) ~ site + as.character(survey), data = herbi_bio)
summary.aov(anovatghbio)
TukeyHSD(anovatghbio)
```

```{r}
omni_bio <- subset(final_best, trophic_guild=="omnivore")
anovatgobio <- aov(sqrt(biomass) ~ site + as.character(survey), data = omni_bio)
summary.aov(anovatgobio)
TukeyHSD(anovatgobio)
```

```{r}
ggplot(data = final_best, aes(x = survey, y=biomass, fill = survey)) + geom_bar(stat = "summary", fun.y = "mean") + labs(y = "Mean Biomass (g)") + stat_summary(geom = "errorbar", fun.data = mean_se) + theme_bw() + theme(legend.position = "none")
```


```{r}
ggplot(data = final_best, aes(x = survey, y=density, fill = survey)) + geom_bar(stat = "summary", fun.y = "mean") + labs(y = "Mean Density (no/30m^2)") + stat_summary(geom = "errorbar", fun.data = mean_se) + theme_bw() + theme(legend.position = "none")
```

```{r}
ggplot(data = final_best, aes(x = survey, y=biomass, fill = survey)) + geom_bar(stat = "summary", fun.y = "mean") + labs(y = "Mean Biomass (g)") + facet_grid(.~site, scales = "free") + theme(legend.position = "none") + stat_summary(geom = "errorbar", fun.data = mean_se) 
```

Anova analysis on overall biomass between surveys and sites: data square root transformed to meet the assumptions

```{r}
anova1 <- aov(sqrt(biomass) ~ as.character(survey) * site, data = final_best)
summary.aov(anova1)
TukeyHSD(anova1)
```

```{r}
ggplot(data = final_best, aes(x = survey, y=density, fill = survey)) + geom_bar(stat = "summary", fun.y = "mean") + labs(y = "Mean Density (n/30m2)") + facet_grid(.~site, scales = "free") + theme(legend.position = "none") + stat_summary(geom = "errorbar", fun.data = mean_se) 
```


```{r}
anovaden <- aov(sqrt(density) ~ as.character(survey) * site, data = final_best)
summary.aov(anovaden)
TukeyHSD(anovaden)
```


```{r}
ggplot(data = final_best, aes(x = survey, y=biomass, fill = trophic_guild)) + geom_bar(stat = "summary", fun.y = "mean") + facet_grid(trophic_guild~site, scales = "free") + theme(legend.position = "none") + stat_summary(geom = "errorbar", fun.data = mean_se) 
```

```{r}
ggplot(data = final_best, aes(x = site, y=biomass, fill = site)) + geom_bar(stat = "summary", fun.y = "mean", position = "dodge") + facet_grid(survey~trophic_guild, scales = "free") + theme(legend.position = "none") + stat_summary(geom = "errorbar", fun.data = mean_se)  
```

```{r}
ggplot(data = final_best, aes(x = site, y=biomass, fill = site)) + geom_bar(stat = "summary", fun.y = "mean", position = "dodge") + facet_grid(trophic_guild~survey, scales = "free") + theme(legend.position = "none") + stat_summary(geom = "errorbar", fun.data = mean_se)  
```

```{r}
ggplot(data = final_best, aes(x = survey, y=biomass, fill = trophic_guild)) + geom_bar(stat = "summary", fun.y = "mean", position = "dodge") + facet_grid(.~site, scales = "free") + theme(legend.position = "none") + stat_summary(geom = "errorbar", fun.data = mean_se, position = "dodge") + scale_y_log10()
```

```{r}
ggplot(data = final_best, aes(x = survey, y=biomass, fill = trophic_guild)) + geom_bar(stat = "summary", fun.y = "mean", ) + facet_grid(.~site, scales = "free") + scale_y_log10()
```

```{r}
ggplot(data = final_best, aes(x = survey, y=biomass, fill = trophic_guild)) + geom_bar(stat = "summary", fun.y = "mean", position = "fill") + facet_grid(.~site, scales = "free") + labs(y = "% biomass") + scale_x_discrete(name = "survey", limit=c("1", "2", "3", "4", "5", "6")) + theme_bw()
```

```{r}
ggplot(data = final_best, aes(x = survey, y=density, fill = trophic_guild)) + geom_bar(stat = "summary", fun.y = "mean", position = "fill") + facet_grid(.~site, scales = "free") + labs(y = "% biomass") + scale_x_discrete(name = "survey", limit=c("1", "2", "3", "4", "5", "6")) + theme_bw()
```

```{r}
final_best_clean <- filter(final_best, biomass>0)
```


```{r}
best_matrix <- final_best_clean %>% group_by(survey, site, species)
```
```{r}
best_matrix2 <- summarise(best_matrix, bio = mean(biomass), den = mean(density))
```
```{r}
matrix_best_pcoa <- read_csv("~/github/BEST_data/data/percent_bio_clean.csv")
library(tidyr)
# The arguments to spread():
# - data: Data object
# - key: Name of column containing the new column names
# - value: Name of column containing values
matrix_wide_pcoa <- spread(matrix_best_pcoa, species, percent_bio)
matrix_wide_pcoa
```

```{r}

matrix_wide_pcoa[is.na(matrix_wide_pcoa)] <-0
matrix_wide_pcoa

```

```{r}
matrix_wide_pcoa$id <- c("HS1_1", "NNE_1", "XL_1", "HS1_2", "NNE_2", "XL_2", "XL_3", "HS1_4", "XL_4", "HS1_5", "NNE_5", "XL_5", "HS1_6", "NNE_6", "XL_6")
matrix_wide_pcoa
```
```{r}
library(tidyverse)
#need to figure out the row name issue
matrix_wide_pcoa[1] = NULL
matrix_wide_pcoa[1] = NULL
row.names(matrix_wide_pcoa) <- matrix_wide_pcoa$id
matrix_wide_pcoa$id = NULL
```

```{r}
library(tidyverse)  # data manipulation
library(cluster)    # clustering algorithms
library(factoextra)
```


```{r}
library(ggplot2)
cluster_best <- kmeans(matrix_wide_pcoa[,-1], centers = 3, nstart = 25)
str(cluster_best)
pcaplot <- fviz_cluster(cluster_best, data = matrix_wide_pcoa[,-1], fill = "darkblue") + ylim(-2.5,4.5) + theme_classic()
pcaplot
```
```{r}
library(vegan)

```


```{r}
# apply PCA - scale. = TRUE is highly 
# advisable, but default is FALSE. 
pca_best <- prcomp(matrix_wide_pcoa,
                 center = TRUE,
                 scale. = TRUE) 
```
plotting pricipal component analysis
```{r}
autoplot(pca_best, data = matrix_wide_pcoa, label = TRUE, colour = 'site')
```
Adding 
```{r}
library(ggfortify)
pca.plot2 <- autoplot(pca_best, data = matrix_wide_pcoa, colour = 'site', frame = TRUE, frame.type = "convex")
pca.plot2
```

```{r}
pam_plot <- fviz_pca_ind(pca_best, label="none", habillage=matrix_wide_pcoa$site,
     addEllipses=TRUE, ellipse.level=0.95, palette = "Dark2")
pam_plot
```







